name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     rails:
    #       - 'rails_v5.2.x'
    #       - 'rails_v6.0.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup (ruby)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Setup System
        run: |
          sudo apt-get install libsqlite3-dev
          echo "::set-env name=MTSR_RAILS_VERSION::${{ matrix.rails }}"
      - name: Setup (env)
        run: |
          echo "::set-env name=AWS_DEFAULT_REGION::us-east-1"
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "::set-env name=AASA_SECRET_ARN::${{ secrets.AASA_SECRET_ARN }}"
          echo "::set-env name=AASA_RESOURCE_ARN::${{ secrets.AASA_RESOURCE_ARN }}"
          echo "::set-env name=AASA_SECRET_ARN2::${{ secrets.AASA_SECRET_ARN2 }}"
          echo "::set-env name=AASA_RESOURCE_ARN2::${{ secrets.AASA_RESOURCE_ARN2 }}"
      - name: Setup (project)
        run: |
          gem install bundler
          ./bin/_setup
      # ./bin/bootstrap
      # - name: Wakeup DB
      #   run: |
      #     if ! ./test/bin/wakeup ; then sleep 45 ; fi
      - name: Test
        run: |
          ./bin/_test
      # - name: Bundle
      #   run: |
      #     export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/${AROR_RAILS_VERSION}.gemfile"
      #     bundle install --jobs 4 --retry 3
      # - name: Test
      #   run: |
      #     export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/${AROR_RAILS_VERSION}.gemfile"
      #     bundle exec rake
